### ISSUE TITLE
3.6.4 docs

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1691]
- [x] Multiple extends in a blueprint (@afbora) 
https://github.com/getkirby/kirby/pull/4218
```yaml
fields:
  layout:
    type: layout
    label: Layout
    extends:
      - layout/layouts
      - layout/fieldsets
      - layout/settings
 ```
