### ISSUE TITLE
Slug field: docs for wizard option

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1742]
```
 slug:
        type: slug
        wizard:
          field: somefield
          text: Generate
```
