### ISSUE TITLE
Document block label usage

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#1781]
````yaml
label: "{{ title }}"

label: "{{ structure.length }}"

label: "{{ gallery.length }} images"

label: "{{ image.0.filename }}"
````
