### ISSUE TITLE
Docs: `color` option for preview icon in sections

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#1921]
https://getkirby.com/docs/reference/panel/sections/pages#preview-images

```yml
image:
  query: page.image.findBy("name", "cover")
  cover: true
  ratio: 1/1
  back: black
  color: red # <-- undocumented
```

possible values...
`color: black`
`color: '#BADA55'`
`color: '{{ page.panelIconColor }}'` query string with custom page method works as well
