### ISSUE TITLE
The files query does not seem to be correct on site.yml

### ISSUE THREAD

**Issue by tristantbg** [getkirby/getkirby.com#198]
Using a `files` field on the `site.yml` blueprint results in an error :
The files query does not seem to be correct on site.yml

How to fix :
Add `query: site.files` to the options

**Comment by distantnative** [comment]
@tristantbg I am not quite sure if I understand you: On which page you think the information is wrong?

**Comment by texnixe** [comment]
Not sure if this is a documentation thing.

If you add a files field in the `site.yml` blueprint without any options:

```
      fields:
        type: fields    
        fields:
          files:
            type: files
```

And try to select a file, the error filed above pops up.

We either have to document that when using a files field in `site.yml` the user has to set a query.

Or, better, the field knows where it is and assumes the `$site` object as default parent, not the page. 

I'd move this to the Kirby repo.
