### ISSUE TITLE
Document users field default value as current user

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#2303]
````yaml
author:
  type: users
  default: true
````

https://getkirby.com/releases/4.0
> Users field: set default: true to always use the currently logged in user as default
