### ISSUE TITLE
No documentation for readonly

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/getkirby.com#319]
Every (?) [form field](https://getkirby.com/docs/panel/blueprints/form-fields) could be a *readonly* field. But it’s not documented.

``` yaml
fields:
  street:
    label: Street
    type: text
    readonly: true
```
