### ISSUE TITLE
User Permissions Panel Typos

### ISSUE THREAD

**Issue by jarneuyt** [getkirby/getkirby.com#343]
I think there’s a typo in this document: https://getkirby.com/docs/guide/users/permissions#defining-permissions 1

> “file” should be “files”.
> "page" should be "pages".

```
title: Editor

permissions:
  access: 
    panel: true
    site: true
    settings: false
    users: false

  site:
    update: false

  page:
    create: true
    changeTemplate: true
    changeTitle: true
    changeSlug: true
    hide: true
    sort: true
    update: true
    delete: false

  user:
    create: false
    createAvatar: true
    deleteAvatar: false
    changeName: false
    changeEmail: false
    changePassword: false
    changeRole: false
    delete: false
    update: false

  file:
    create: true
    changeName: true
    delete: true
    replace: true
    update: false
```
