### ISSUE TITLE
Check docs for 3.0.3 changes

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#365]
- Add icon specific type class to the icon component
- The `rel` attribute in `HTML::a()` will now overwrite predefined `noopener` and `noreferrer` values when a target is defined.
- The title and description in user blueprints can now be translated correctly.
```
    title: 
      en: Client
      de: Kunde
    description: 
      en: The client can edit all pages
      de: Der Kunde kann alle Seiten bearbeiten
```
- Thumb presets from v2 are back. You can define them like this in your config
```php
    <?php 
    
    return [
        'thumbs' => [
            'presets' => [
                'default' => ['width' => 1024, 'quality' => 80],
                'blurred' => ['blur' => true]
            ]
        ]
    ];
```
… and use them afterwards …
```php
    // default
    $file->thumb()
    
    // preset
    $file->thumb('blurred')
```
- New `$this→next()` handler in routes to jump to the next applicable route.
```php
    return [
        'routes' => [
            [
                'pattern' => '(:any)',
                'action'  => function ($slug) {
    
                    if ($page = page('photography')->find($slug)) {
                        return page($page);
                    }
    
                    $this->next();
    
                }
            ]
        ]
    ];
```
