### ISSUE TITLE
Query language in the image option uses `query` instead of `src`

### ISSUE THREAD

**Issue by REHvision** [getkirby/getkirby.com#39]
The [Querying an image in the image option](https://nnnnext.getkirby.com/docs/guide/blueprints/query-language#querying-an-image-in-the-image-option) part shows:
```
image:
  src: page.images.template("cover").first
  ratio: 1/1
  cover: true
```
I can't get `src` to work in any way but using `query` instead works perfectly.
