### ISSUE TITLE
Mistakes in User Blueprint in Permissions

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/getkirby.com#607]
In the docs I think I just found some mistakes in "Permissions" in "User Blueprint":

In `user:` there is missing `changeLanguage:`

And in `users:` there shouldn't be any commas after each line, so it should be:

```
  users:
    create: false
    changeName: false
    changeEmail: false
    changeLanguage: false
    changePassword: false
    changeRole: false
    delete: false
    update: false
```

https://getkirby.com/docs/guide/users/permissions#defining-permissions__user-blueprint
