### ISSUE TITLE
Validate field option not documented

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#673]
```
    fields:
      color:
        label: Color
        type: text
        validate:
          match: "/^[0-9–]+$/m"
```

**Comment by texnixe** [comment]
getkirby/kirby#2041

**Comment by texnixe** [comment]
Examples:

```
somefield:
  type: text
  validate:
    isGreen
```

With a custom validator `isGreen`:

```
<?php
Kirby::plugin('tex/val', [
  'validators' => [
    'isGreen' => function ($value) {
      return V::in($value, ['green','lightgreen', 'darkgreen', 'mediumgreen']);
    }
  ]
]);
```

Q: How can I use `V::in` without a custom validator in a blueprint? Something like

```
validate:
  in:
    - a
    - b
    - c
```
throws an error ("Argument 2 passed to Kirby\Toolkit\{closure}() must be of the type array, integer given"), 

while

```
validate:
  between:
    - 1
    - 5
```
works.

Bug?
