### ISSUE TITLE
Fix doc for 'num' option in blueprint pages, if field needs to be specified

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#69]
Documentation needs to be changed: http://getkirby.com/docs/panel/blueprints/page-settings#numbering-of-subpages

Should be:

```
pages:
  num:
    mode: date
    field: added
```

See: https://github.com/getkirby/kirby/issues/245

**Comment by distantnative** [comment]
Documentation needs to be changed: http://getkirby.com/docs/panel/blueprints/page-settings#numbering-of-subpages

Should be:

```
pages:
  num:
    mode: date
    field: added
```

See: https://github.com/getkirby/kirby/issues/245
