### ISSUE TITLE
Docs: Inputlist field types (radio, checkboxes..) - option 'columns'

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#78]
``` 
test:
    label: Many
    type: checkboxes
    options: pages
    columns: 3
```

Options: `1`, `2`, `4`, (`3`, `5`)
