### ISSUE TITLE
Docs: toStructure()

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#82]
Especially the new toStructure method is awesome. While the yaml method returned a simple associative PHP array for structured field content, the new toStructure method gives you a full blown Kirby Collection which makes it possible to use Kirby's chaining syntax:

For example…

```
Accounts:
- name: Twitter
  url: http://twitter.com/getkirby
- name: Github
  url: http://github.com/getkirby
```

can simply be turned into this:

```html
<h1>On the web</h1>
<ul>
  <?php foreach($page->accounts()->toStructure() as $account): ?>
  <li>
    <a href="<?php echo $account->url() ?>">
      <?php echo $account->name()->html() ?>
    </a>
  </li>
  <?php endforeach ?>
</ul>
```
