### ISSUE TITLE
Docs: Structure fields - default values

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#84]
You can now set default values for structure fields in YAML:

```
  emails: 
    label: Emails
    type: structure
    default: 
      - email: bastian@getkirby.com
      - email: sascha@getkirby.com
      - email: nico@getkirby.com
    fields: 
      email: 
        label: Email
        type: email
```
