### ISSUE TITLE
Docs: Dynamic field options additions

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#87]
Select fields, checkboxes and radio buttons now have improved dynamic options and option queries.

#### visibleSiblings and invisibleSiblings mode for options

Example A:

```
label: Select field
type: select
options: visibleSiblings
```

Example B:

```
label: Select field
type: select
options: query
query: 
  page: projects/project-a
  fetch: invisibleSiblings
```

#### More flexible page option in queries

The page option now supports relative paths.
You can only move up in the pages tree though.

Example:

```
  label: Select field
  type: select
  options: query
  query: 
    page: ../../../
    fetch: children
```

#### External API support for dynamic field options

You can now simply pass a URL for options to fetch a JSON array with keys and values for options:

```
  label: Select field
  type: select
  options: http://myoptionsapi.com/options.json
```

Make sure the JSON is in the following format:

```
{
 'key1' : 'value1',
 'key2' : 'value2',
 'key3' : 'value3' 
}
```
