### ISSUE TITLE
wrong intendation fields.pattern

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#881]
https://getkirby.com/docs/guide/blueprints/fields#validating-fields__pattern-matches

```yaml
text:
  type: text
   pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
```

should be
```yaml
text:
  type: text
  pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
```
